// Create Resume data in JSon format
let resume = {
    "GANESH": false,
    "15/2,Manickam street,": {},
    "Udumalpet,": {},
    "Tamil": 0,
    "Mobile:+91 997 676 2127,": {},
    "email:eganeshbabu7@gmail.com____________________________________________________________": {},
    "CAREER": {},
    "To": "",
    "EDUCATIONAL": {},
    "Course": {},
    "B.E(Mechanical)\tSri Eshwar College of Engineering, Coimbatore\tAnna University, Chennai\t2017\t7.8": {},
    "(CGPA)": {},
    "DIPLOMA(Mechanical)\tRudhraveniMuthusamy Polytechnic College, Udumalpet": {},
    "DOTE": {
      "2014": {}
    },
    "SSLC": {},
    "State": false,
    "PROFESSIONAL": {},
    "HCL": {},
    "•Currently I am working as, a LEAD DESIGN ENGINEER in Medical Device Project.": {},
    "•Here my role is working in Design Changing, Defect Prevention Analyst & Configuration Controller and doing Management Activities.": {},
    "•Initially we are creating red line drawings and getting approval from Client.": {},
    "•After getting approval need to create DCR in PLM like (Agilee6 and Wind-chill).": {},
    "•After creating DCR we need to prepare supporting documents like (Red line Drawing, Engineering Rationale, PQP, CTQ and Material Disposition).": {},
    "•After completing all drawing updates and document creation need to upload and route DCR in PLM to get approval from On-site coordinators.": {},
    "•After getting approval from On-site coordinators need to create DCO followed by the same DCR.": {},
    "•After creating DCO need to update model and drawings in software like (NX-CAD and Creo5.0).": {},
    "•After completing model update need to upload (3D Models & To condition.": {},
    "Drawing)and route DCO in PLM to get approval from On-site coordinators.": {},
    "ROOTS": {},
    "•Worked as Associate-Design Engineer in PRODUCT DEVELOPMENT ENGINEERING.": {},
    "•My role in this company is after getting project request from marketing team I will undergo costing and feasibility analysis.": {},
    "•After getting clearance from management I have to create concept models for the given product as per customer requirement.": {},
    "•After getting approval for concept design from Management I will finish detail drawings with in scheduled time.": {},
    "•After releasing reference drawings, we will make Proto-type against the product and testing will be done thoroughly in customer point of view until first batch production.": {},
    "UMS": {},
    "•My role in this company as a Mechanical Design Engineering-Trainee in NEW PRODUCT DEVELOPMENT DIVISION.": {},
    "AEROSPACE": "2022-08-06T03:02:41.238Z",
    "I have designed a Bulk Head Assembly of Aircraft part for new RADAR development.": {},
    "In this project I have taken measurements from aircraft and integrated with Radom and Radar accessories.": {},
    "After creating model optimizing those parts with respect to manufacturing and as well as assembly point of view.": {},
    "Weigh cost constraints while preparing project design schedules.": {},
    "TURBINE": {},
    "Reproduced and updated archived designs to confirm with current requirements.": {},
    "Verified requested integration capabilities of designed components.": {},
    "Assisted with preparations for client presentations.": {},
    "L.G.BALAKRISHNAN& BROS PVT LTD, COIMBATORE - 641006.": {},
    "•My role in that company as a Mechanical Design Engineering-Trainee in    MACHINE BUILDING DIVISION from June-2017 to March-2018.": {},
    "•I am having sound knowledge in (Auto cad & Solid works) software’s.": {},
    "•In Solid works I have well experienced with (Part modelling, Assembly, Sheet metal, Weldments and Drawing).": {},
    "•And I have used Configuration tool in Solid works to reduce the design time in (Part modelling, Assembly and Drawing) environment.": {},
    "•In Auto cad also I can able to create (Part drawings & Assembly drawings).": {},
    "•I am having quite well knowledge in (Detailing, Geometrical Tolerances) in Auto Cad.": {},
    "•I can able to create Bill of Materials for Part drawings and Bought out items.": {},
    "SOFTWARE": "",
    "•Auto CAD, Solid works, Creo5.0, NX-CAD, Agilee6, Wind-chill & M.S. Office.": {},
    "EXTRA": {},
    "•First class with Distinction in TYPE WRITING ENGLISH& TAMIL Senior": {},
    "PERSONAL": "2022-08-06T03:02:41.239Z",
    "FATHER": 0,
    "MOTHER": 0,
    "DATE": {},
    "LANGUAGE": {},
    "PLACE:COIMBATORE.\t\t\tYours faithfully,": {},
    "DATE  : \t\t\tE. Ganesh Babu.": {}
  }

  console.log(resume);
  